--print(pkm.get_script())
pkm.set_script(0)
--print(pkm.get_player_pos().x / 16)
--pkm.set_emote(0,0)
--pkm.set_emote(2,0)
pkm.set_freeze(0,false)
--pkm.add_movement(0,0,1)
--pkm.add_movement(0,3,1)
--pkm.add_movement(0,0,1)
--pkm.add_movement(0,3,1)
--pkm.add_movement(0,0,1)
--pkm.add_movement(0,1,5)