--print(pkm.get_script())
pkm.set_script(10)
pkm.give_pokemon("CHARIZARD",33)
--print(pkm.get_player_pos().x / 16)
--pkm.set_emote(0,0)
--pkm.set_emote(2,0)
--pkm.set_freeze(1,true)
--pkm.set_freeze(2,true)
--pkm.add_movement(0,0,1)
--pkm.add_movement(0,3,1)
--pkm.add_movement(0,0,1)
--pkm.add_movement(0,3,1)
--pkm.add_movement(0,0,1)
--pkm.add_movement(0,1,5)